language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - ./share/travis_setup.sh

script:
  # run unit tests
  - py.test -svv test/unit/

  # style guide check
  - find ./lib ./test ./bin -name \*.py -exec pycodestyle --show-source --ignore=E501,E402,E722,E129,W503,W504 {} +
